SHADER_OPTION_COMMAND_NAME : "serverShader"
SHADER_PATCHER_COMMAND_NAME : "serverPatcher"
SHADER_OPTION_COMMAND_ERROR_ALREADY : "Nothing has changed; you already have this parameter selected"
SHADER_PATCHER_COMMAND_ERROR_PLAYER_NOWHERE_TO_BE_FOUND : "The player cannot be found"
SHADER_PATCHER_ERROR_VERSION : "Your visual settings were reset to default values due to a change in the server configuration. If you want to change this option again, do /"

SHADER_OPTION:
  - disable
  - hybrid
  - enable

SHADER_OPTION_PERSISTENT_DATA_NAME : "ShaderOption"
PLAYER_SETUP_PERSISTENT_DATA_NAME : "isSetup"
PLAYER_VERSION_PERSISTENT_DATA_NAME : "optionVersion"

SHADER_OPTION_DEFAULT_ID : 2