name: shaderTweaker
version: '1.0-SNAPSHOT'
main: me.titruc.shaderPatcher.ShaderPatcher
api-version: '1.21'

permissions:
  shaderpatcher.option.use:
    description: use the changeshaderoption command
    default: true

  commands:
    testcmd:
      description: Test command