name: shaderPatcher
version: '1.0-SNAPSHOT'
main: me.titruc.shaderPatcher.ShaderPatcher
api-version: '1.21'

permissions:
  shaderpatcher.option:
    description: can use shader option command
    default: true

  shaderpatcher.admin:
    description: can use all shader patcher commands
    default: op